name: "Wollfish Cloudflare Purge Cache"
description: "Purge a zone's cache via the Cloudflare API"
author: jindalrj
runs:
  using: docker
  image: Dockerfile
branding:
  color: orange
  icon: trash-2
